apiVersion: v1
kind: Namespace
metadata:
  name: chaos
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: exp1-polygon-outage
  namespace: chaos
  labels:
    app.kubernetes.io/component: api-orchestrator-chaos
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: api-orchestrator
  loss:
    loss: "100"
    correlation: "100"
  duration: "5m"
  externalTargets:
    - "api.polygon.io"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: exp4-provider-latency
  namespace: chaos
  labels:
    app.kubernetes.io/component: api-orchestrator-chaos
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: api-orchestrator
  delay:
    latency: "2000ms"
    correlation: "10"
    jitter: "100ms"
  duration: "5m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: exp9-rollout-pod-kill
  namespace: chaos
  labels:
    app.kubernetes.io/component: api-orchestrator-chaos
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: api-orchestrator
  duration: "30s"
